---
- name: Install Duply
  package:
    name={{ item }}
    state=latest
  with_items:
    - python-boto
    - duply

- name: Create Duply configuration directory structure
  file: path=/etc/duply/{{ duply_profile }}
        mode=0700
        state=directory

- name: Configure Duply
  template: src={{ item }}.j2
            dest=/etc/duply/{{ duply_profile }}/{{ item }}
            mode=0600
  with_items:
    - conf
    - exclude
